spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

    data: classpath:/data.sql

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true